server.port=8090

# 1. Base GenAI Configuration (Builds the Chat Model and Client automatically)
spring.ai.google.genai.api-key=
spring.ai.google.genai.chat.options.model=gemini-2.0-flash

# 2. Embedding Configuration (Builds the Vector Translator automatically)
spring.ai.google.genai.embedding.api-key=
spring.ai.google.genai.embedding.text.options.model=gemini-embedding-001
spring.ai.google.genai.embedding.text.options.dimensions=768

# 3. Vector DB Configuration (Connecting to pgvector)
spring.datasource.url=jdbc:postgresql://localhost:5432/hr_database
spring.datasource.username=hr_admin
spring.datasource.password=hr_password

spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimension=768

spring.ai.retry.client.enabled=false
