server.port=8080

# 1. LLM Configuration
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o

# 2. Vector DB Configuration (Connecting to pgvector)
spring.datasource.url=jdbc:postgresql://localhost:5432/hr_database
spring.datasource.username=hr_admin
spring.datasource.password=hr_password
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimension=1536

# 3. MCP Server Connection
spring.ai.mcp.client.stdio.connections.hr-mcp.command=java
spring.ai.mcp.client.stdio.connections.hr-mcp.args=-jar, /c/Users/Rishabh.Gupta1/Desktop/aiAgent/hr-workspace/hr-mcp-server/target/hr-mcp-server-0.0.1-SNAPSHOT.jar
