# spring.main.web-application-type=none
# spring.main.banner-mode=off
# logging.pattern.console=

spring.main.banner-mode=off
logging.level.root=OFF
logging.level.org.springframework=OFF
logging.level.org.hibernate=OFF

spring.ai.mcp.server.stdio=true
spring.ai.mcp.server.name=hr-mcp-server
spring.ai.mcp.server.version=1.0.0


spring.datasource.url=jdbc:postgresql://localhost:5432/hr_database
spring.datasource.username=hr_admin
spring.datasource.password=hr_password
spring.jpa.hibernate.ddl-auto=update

# # Pre-populate a dummy employee (EMP-992) for testing
# spring.sql.init.mode=always

# Tell the JSON parser to ignore unknown fields sent by newer MCP clients
spring.jackson.deserialization.fail-on-unknown-properties=false

server.port=8080
